# nvfetcher.toml
[manix]
src.git = "https://github.com/mlvzk/manix"
fetch.github = "mlvzk/manix"

# (Neo)vim
[neozoom-nvim]
src.git = "https://github.com/nyngwang/NeoZoom.lua"
fetch.github = "nyngwang/NeoZoom.lua"

[magma-nvim]
src.git = "https://github.com/dccsillag/magma-nvim"
fetch.github = "dccsillag/magma-nvim"

[one-small-step-for-vimkind]
src.git = "https://github.com/jbyuki/one-small-step-for-vimkind/"
fetch.github = "jbyuki/one-small-step-for-vimkind"

[cmp-path]
src.git = "https://github.com/hrsh7th/cmp-path"
fetch.github = "hrsh7th/cmp-path"
