# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  cmp-dap = {
    pname = "cmp-dap";
    version = "e21f0e5d188ee428f8acab1af21839af391607a4";
    src = fetchFromGitHub ({
      owner = "rcarriga";
      repo = "cmp-dap";
      rev = "e21f0e5d188ee428f8acab1af21839af391607a4";
      fetchSubmodules = false;
      sha256 = "sha256-oFHXTiPkYDvD7CLXKgp88tQnMEX2e/N5Z43VGI45m6Y=";
    });
  };
  cmp-path = {
    pname = "cmp-path";
    version = "447c87cdd6e6d6a1d2488b1d43108bfa217f56e1";
    src = fetchFromGitHub ({
      owner = "hrsh7th";
      repo = "cmp-path";
      rev = "447c87cdd6e6d6a1d2488b1d43108bfa217f56e1";
      fetchSubmodules = false;
      sha256 = "sha256-G/I2SH4Uidr25/4fjrtcK3VfxWwD9MSN+ODcB6zjvVo=";
    });
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub ({
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    });
  };
  neozoom-nvim = {
    pname = "neozoom-nvim";
    version = "de0e27a3e619ed3f79232ba8daf0ae1a8e92bfea";
    src = fetchFromGitHub ({
      owner = "nyngwang";
      repo = "NeoZoom.lua";
      rev = "de0e27a3e619ed3f79232ba8daf0ae1a8e92bfea";
      fetchSubmodules = false;
      sha256 = "sha256-A8RiK5dNRglJJfsaGxnyj3lOah1m8Zvmj1upeN4tYVI=";
    });
  };
}
