# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub ({
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    });
  };
  neozoom-nvim = {
    pname = "neozoom-nvim";
    version = "de0e27a3e619ed3f79232ba8daf0ae1a8e92bfea";
    src = fetchFromGitHub ({
      owner = "nyngwang";
      repo = "NeoZoom.lua";
      rev = "de0e27a3e619ed3f79232ba8daf0ae1a8e92bfea";
      fetchSubmodules = false;
      sha256 = "sha256-A8RiK5dNRglJJfsaGxnyj3lOah1m8Zvmj1upeN4tYVI=";
    });
  };
}
